### ISSUE TITLE
Issues on the section items (after generating the pdf)

### ISSUE THREAD

**Issue by marcosrosse** [posquit0/Awesome-CV#551] opened 2024-11-29 11:09 UTC
Hi 👋🏿 ,

First, thanks for the project, it's really an awesome-cv!

It seems that the PDF is being generated with some issues with the new versions of the **texlive** container.
The section items are overlapping each other in the following sections:
-  Experience, 
- Extracurricular Activity, 
- Presentation and Writing

Example:
![image](https://github.com/user-attachments/assets/fcd8b5f6-6908-484a-953a-b6ee3f655e95)

How to reproduce:
Generate a new PDF using the GitHub actions.

**Comment by nigiord** [comment] 2024-11-30 14:25
Hi, same issue on my side, any idea which version of texlive caused the issue?

```
$ xelatex --version
XeTeX 3.141592653-2.6-0.999996 (TeX Live 2025/dev/Debian)
kpathsea version 6.4.0/dev
Copyright 2024 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 72.1; using 72.1
Compiled with zlib version 1.3.1; using 1.3.1
Compiled with FreeType2 version 2.13.3; using 2.13.3
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 10.0.1; using 10.0.1
Compiled with libpng version 1.6.44; using 1.6.44
Compiled with pplib version v2.2
Compiled with fontconfig version 2.15.0; using 2.15.0
```

**Comment by HaochengLIU** [comment] 2024-12-01 18:48
Second Nigoord that I encounter the same problem on MacOS. Appending `\vspace{0.3cm}` temporarily fixes the problem...
```
➜  examples git:(2024-nov) ✗ xelatex --version
MiKTeX-XeTeX 4.7.1 (MiKTeX 22.1)
© 1994-2008 SIL International, © 2009-2021 Jonathan Kew, © 2010-2012 Hàn Thế Thành, © 2012-2013 Khaled Hosny
TeX is a trademark of the American Mathematical Society
using bzip2 version 1.0.8, 13-Jul-2019
compiled with curl version 7.77.0; using libcurl/8.4.0 SecureTransport (LibreSSL/3.3.6) zlib/1.2.12 nghttp2/1.58.0
compiled with expat version 2.4.1; using expat_2.5.0
compiled with fontconfig version 2.13.1; using 2.13.1
compiled with freetype2 version 2.11.1; using 2.11.1
compiled with graphite2 version 1.3.14; using 1.3.14
compiled with harfbuzz version 2.7.2; using 2.7.2
compiled with icu version 69.1; using 69.1
compiled with jpeg version 9.5
compiled with liblzma version 50020052; using 50040032
compiled with libpng version 1.6.37; using 1.6.37
compiled with MiKTeX Application Framework version 4.3; using 4.3
compiled with MiKTeX Core version 4.11; using 4.11
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.6; using 4.6
compiled with openssl version OpenSSL 1.1.1m  14 Dec 2021; using OpenSSL 1.1.1m  14 Dec 2021
compiled with pplib version v2.05 less toxic i hope
using teckit version 2.4
compiled with uriparser version 0.9.6
compiled with zlib version 1.2.11; using 1.2.12
```

**Comment by OJFord** [comment] 2024-12-01 21:50
Duplicate of #532

**Closed** 2024-12-01 21:50 UTC
