### ISSUE TITLE
Compilation fails after the latest TexLive update

### ISSUE THREAD

**Issue by Vintodrimmer** [posquit0/Awesome-CV#221] opened 2018-07-30 19:10 UTC
Good day,

I just ran `tlmgr update --all` and the same file I compiled the moment before started showing the following error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "xparse/command-already-defined"
!
! Command '\FA' already defined!
!
! See the LaTeX3 documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.166 \newfontfamily
                    \headerfont[
```

It seems to work if I comment out the `\newfontfamily\FA{FontAwesome}` line in `awesome-cv.cls`.

**Comment by ima18h** [comment] 2018-08-23 10:16
I have this as well. I added another A so i can compile...
```
\newfontfamily\FA{FontAwesome}
```
to
```
\newfontfamily\FAA{FontAwesome}
```

**Comment by Siltyx** [comment] 2018-11-04 12:03
Got this problem as well, the FAA trick lets me compile as well, thank you

**Comment by cbarrick** [comment] 2019-01-30 06:36
I think this is a duplicate of #181. The error is different, but the underlying reason is the same.

**Comment by OJFord** [comment] 2022-02-11 21:12
Closed via #344.

**Closed by OJFord** 2022-02-11 21:12 UTC
