### ISSUE TITLE
Reflect position change within same company

### ISSUE THREAD

**Issue by nthakran** [posquit0/Awesome-CV#448] opened 2022-12-12 17:45 UTC
Hi,
How can I reflect two different positions under the same company in case of promotions, etc.?
Thanks
![Bildschirmfoto 2022-12-12 um 18 44 04](https://user-images.githubusercontent.com/46453731/207116464-39dc5eac-9d42-4537-9335-66abfbe5a73d.jpeg)

**Comment by LucasDziesinski** [comment] 2022-12-12 18:56
There is a suggestion on how to implement this here: https://github.com/posquit0/Awesome-CV/issues/443 and https://github.com/posquit0/Awesome-CV/issues/297. Hope it helps!

**Comment by OJFord** [comment] 2022-12-12 20:43
I do intend to get some sort of canonical solution built in - there are suggestions elsewhere as mentioned, and I also have my own - so please don't take it as dismissive of the idea, but I'll close this as a duplicate of older discussion.

Thanks @LucasDziesinski for linking those.

**Closed** 2022-12-12 20:44 UTC

**Comment by nthakran** [comment] 2022-12-12 20:45
The solution #297 worked just fine! Thanks both!
